apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-cred-test
  title: Test AWS credentials
spec:
  owner: guests
  type: service

  steps:
    - id: identity
      name: Who am I?
      action: aws:whoami

  output:
    text: |
      ✅ Credentials work!

      • AWS Account:  ${{ steps.identity.output.account }}
      • Caller ARN:   ${{ steps.identity.output.arn }}
      • User ID:      ${{ steps.identity.output.userId }}
