apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ipam-cidr-tool
  title: IPAM – allocate or release CIDR
  description: Reserve a new CIDR in an AWS IPAM pool or release an existing allocation
spec:
  owner: platform-team
  type: service

  # ───────────────────────── parameters ─────────────────────────
  parameters:
    - title: Operation and pool
      required: [operation, ipamPoolId]
      properties:
        operation:
          title: What do you want to do?
          type: string
          enum: [allocate, release]
          default: allocate
        ipamPoolId:
          title: IPAM pool ID
          type: string

    # inputs that appear only on Allocate
    - if:
        properties:
          operation:
            const: allocate
      then:
        title: Allocate parameters
        required: [cidr]
        properties:
          cidr:
            title: CIDR block to allocate
            type: string

    # inputs that appear only on Release
    - if:
        properties:
          operation:
            const: release
      then:
        title: Release parameters
        required: [cidr]
        properties:
          cidr:
            title: CIDR block to release
            type: string

  # ────────────────────────── steps ────────────────────────────
  steps:
    # ALLOCATE path
    - id: allocate
      name: Allocate CIDR
      if: ${{ parameters.operation == 'allocate' }}
      action: aws:ipam:allocate-cidr
      input:
        ipamPoolId: ${{ parameters.ipamPoolId }}
        cidr:       ${{ parameters.cidr }}

    # RELEASE path
    - id: release
      name: Release CIDR
      if: ${{ parameters.operation == 'release' }}
      action: aws:ipam:release-cidr
      input:
        ipamPoolId: ${{ parameters.ipamPoolId }}
        cidr:       ${{ parameters.cidr }}

  # ────────────────────────── outputs ──────────────────────────
  output:
    text:
      - title: Result
        content: |
          ${{ steps.allocate.output.cidr   || steps.release.output.releasedCidr }}
